version: '3.9'

services:
  web:
    build: .
    ports:
      # - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stamaraiadb
      MYSQL_USER: stuser
      MYSQL_PASSWORD: stpass
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      # - "8002:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
